### ISSUE TITLE
Apps can install from XCode, but crashed at start

### ISSUE THREAD

**Issue by sparklone** [linusyang/AppSync#5]
Hi, I install AppSync to deploy without certificate, but all my apps now crashed at start

Nov 4 03:29:20 iPad kernel[0] <Notice>: Sandbox: hook..execve() killing pid 964: application requires container but none set 
Nov 4 03:29:20 iPad com.apple.xpc.launchd[1](UIKitApplication:edu.self.LearnLangsPlayer[0x6754][964]) <Notice>: Service exited due to signal: Killed: 9

But if I cut app from /private/var/mobile/Containers/Bundle/Application/~/~.app and move it to /Applications - it start normally (no signature check for apps from this folder?)

Try XCode 5 & Xcode 6, no luck.
Apps signed by ldid

**Comment by bbodenmiller** [comment]
I have the same error message when attempting to build and run the app at https://github.com/OneBusAway/onebusaway-iphone. This method worked with iOS 7. The [project is built using](https://github.com/OneBusAway/onebusaway-iphone/blob/develop/.travis.yml#L25):

```
xctool -project org.onebusaway.iphone.xcodeproj -scheme Debug archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" build-tests run-tests
```

Then [fake signed using](https://github.com/OneBusAway/onebusaway-iphone/blob/develop/scripts/travis/upload.sh#L102):

```
./ldid -S $APPNAME.app/$APPNAME
```

And lastly packaged using:

```
xcrun -sdk iphoneos PackageApplication -v "$CURRENT_DIR/$APPNAME.app" -o "$CURRENT_DIR/$APPNAME.ipa"
```

Any ideas what I need to adjust to prevent the application from crashing on launch?

**Comment by linusyang92** [comment]
Issue is outdated. Please re-open if it still exists.
