### ISSUE TITLE
install ipa Error

### ISSUE THREAD

**Issue by app111** [linusyang/AppSync#8]
SearchForApp[500] <Warning>: LaunchServices: Not creating progress for <LSApplicationProxy: 0x158d20e0> cn.net.dshow.baoxiandl since it is not a placeholder.

com.apple.xpc.launchd[1](com.apple.xpc.launchd.domain.system) <Error>: Caller not allowed to perform action: SearchForApp.500, action = sandboxed lookup, code = 1: Operation not permitted, uid = 501, euid = 501, gid = 501, egid = 501, asid = 0

**Comment by linusyang92** [comment]
Issue is outdated. Please re-open if it still exists.
